- name: Instalación de paquetes para servidor SFTP
  hosts: ec2_instances
  become: true
  tasks:
  - name: Instalación de paquetes para servidor SFTP
    become: true
    yum:
      name: 
        - openssh-server
        - vsftpd
        - jq
        - automake
        - openssl-devel
        - git
        - gcc
        - libstdc++-devel
        - gcc-c++
        - fuse
        - fuse-devel
        - curl-devel
        - libxml2-devel       
      state: latest
  # - name: Configuración del servidor vsftpd
    # become: true
    # copy:
      # src: vsftpd.conf
      # dest: /etc/vsftpd/vsftpd.conf
  # - name: Reinicio del servicio vsftpd
    # become: true
    # service:
      # name: vsftpd
      # state: restarted
  # - name: Crear un grupo
    # become: true
    # group:
      # name: sftp
  # - name: añadir usuario a grupo
    # become: true
    # user:
      # name: sftpuser
      # password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
      # groups: sftp
  # - name: crear usuario y añadirlo a grupo
    # become: true
    # shell:
      # |
      # echo "Creating SFTP user..."
      
      # sudo groupadd sftp
      # sudo useradd -m sftpuser -s /bin/bash -g sftp
      # sudo echo "mypassword" | passwd sftpuser --stdin
      # sudo chown root /home/sftpuser
      # sudo chmod 755 /home/sftpuser
      # sudo mkdir /home/sftpuser/s3
      # sudo chown sftpuser:sftp /home/sftpuser/s3

  - name: Instalar el repositorio EPEL en Amazon Linux
    become: true
    command: amazon-linux-extras install epel -y
  - name: Instalar paquete s3fs
    yum:
      name: s3fs-fuse
      state: present
  # - name: Configuración de acceso a S3
    # become: true
    # copy:
      # src: passwd-s3fs
      # dest: /etc/passwd-s3fs
  # - name: Cambiar permisos
    # file:
      # path: /etc/passwd-s3fs
      # mode: '0600'
      
 #######################################################3
  - name: montar bucket
    become: true
    shell:
      |
      mkdir /mnt/s3
      EC2METALATEST=http://169.254.169.254/latest && 
      EC2METAURL=$EC2METALATEST/meta-data/iam/security-credentials/ && 
      EC2ROLE=`curl -s $EC2METAURL` && 
      S3BUCKETNAME={{ bucket_name }} && 
      DOC=`curl -s $EC2METALATEST/dynamic/instance-identity/document` && 
      REGION=`jq -r .region <<< $DOC`
      sudo s3fs $S3BUCKETNAME  -o use_cache=/tmp,allow_other /mnt/s3 -o url="https://s3-$REGION.amazonaws.com" -o nonempty -o mp_umask=022
      sudo chmod -R 777 /mnt/s3/*
      cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
      sleep 10
  - name: crear un usuario sftp
    become: true
    shell:
      |
      sudo groupadd sftpgroup
      sudo useradd -G sftpgroup -d /mnt/s3/alumnos/sftpuser -s /sbin/nologin sftpuser
      echo "suhar" | passwd --stdin sftpuser
      mkdir -p /mnt/s3/alumnos/sftpuser
      sudo chown root /mnt/s3/alumnos/sftpuser
      sudo chmod g+rx /mnt/s3/alumnos/sftpuser
      mkdir -p /mnt/s3/alumnos/sftpuser/escritura
      mkdir -p /mnt/s3/alumnos/sftpuser/lectura
      chown sftpuser:sftpuser /mnt/s3/alumnos/sftpuser/escritura
      chown ec2-user:sftpuser /mnt/s3/alumnos/sftpuser/lectura###############################realizado cambio
      sudo usermod -a -G sftpuser ec2-user
      ln -s /mnt/s3 /home/ec2-user/s3
      rm -f /mnt/s3/alumnos/sftpuser/.bash_logout /mnt/s3/alumnos/sftpuser/.bash_profile /mnt/s3/alumnos/sftpuser/.bashrc 
      mkdir -p /mnt/s3/profesor
      chown ec2-user:ec2-user /mnt/s3/profesor


  - name: Configuración del servidor openssh-server
    become: true
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      
      
  - name: Reinicio del servicio SSH
    become: true
    service:
      name: sshd
      state: restarted  
      
  - name: introduccion del script de creacion de usuario
    become: true
    copy:
      src: usuario.sh
      dest: /home/ec2-user/usuario.sh
      mode: 0755
#############################################################
      
  # - name: crear un directorio 
    # become: true
    # command: mkdir /mnt/s3bucket
  # - name: Montaje del bucket de S3 
    # become: true
    # command: s3fs {{ s3_bucket_name }} -o use_cache=/tmp -o allow_other -o uid=1001 -o mp_umask=002 -o multireq_max=5 /mnt/s3bucket
  # - name: Crear directorio /sftpuser
    # file:
      # path: /mnt/s3bucket/sftpuser
      # state: directory
  # - name: Crear archivo example.txt dentro de /sftpuser
    # copy:
      # content: "hello world"
      # dest: /mnt/s3bucket/sftpuser/example.txt
  # - name: Creación del directorio en el bucket de S3
    # become: true
    # file:
      # name: "{{ s3_bucket_name }}"
      # path: "/sftpuser"
      # state: present
    # register: s3_bucket_result
  # - name: Asignación de permisos al directorio en el bucket de S3
    # become: true
    # file:
      # path: "/mnt/s3bucket/sftpuser"
      # state: directory
      # owner: sftpuser
      # group: sftpuser
      # mode: 0770

