- name: Instalaci贸n de paquetes para servidor SFTP
  hosts: ec2_instances
  become: true
  tasks:
  - name: Instalaci贸n de paquetes para servidor SFTP
    become: true
    yum:
      name: 
        - openssh-server
        - vsftpd
        - jq
        - automake
        - openssl-devel
        - git
        - gcc
        - libstdc++-devel
        - gcc-c++
        - fuse
        - fuse-devel
        - curl-devel
        - libxml2-devel       
      state: latest

  - name: Instalar el repositorio EPEL en Amazon Linux
    become: true
    command: amazon-linux-extras install epel -y
  - name: Instalar paquete s3fs
    yum:
      name: s3fs-fuse
      state: present
  - name: Configuraci贸n de acceso a S3
    become: true
    copy:
      src: passwd-s3fs
      dest: /etc/passwd-s3fs
  - name: Cambiar permisos
    file:
      path: /etc/passwd-s3fs
      mode: '0600'
      
  - name: montar bucket
    become: true
    shell:
      |
      mkdir /mnt/s3
      EC2METALATEST=http://169.254.169.254/latest && 
      EC2METAURL=$EC2METALATEST/meta-data/iam/security-credentials/ && 
      EC2ROLE=`curl -s $EC2METAURL` && 
      S3BUCKETNAME={{ bucket_name }} && 
      DOC=`curl -s $EC2METALATEST/dynamic/instance-identity/document` && 
      REGION=`jq -r .region <<< $DOC`
      sudo s3fs $S3BUCKETNAME  -o use_cache=/tmp,allow_other /mnt/s3 -o url="https://s3-$REGION.amazonaws.com" -o nonempty -o mp_umask=022
      sudo chmod -R 777 /mnt/s3/*
      cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
      sleep 10
  - name: crear un usuario sftp
    become: true
    shell:
      |
      sudo groupadd sftpgroup
      sudo useradd -G sftpgroup -d /mnt/s3/alumnos/sftpuser -s /sbin/nologin sftpuser
      echo "suhar" | passwd --stdin sftpuser
      mkdir -p /mnt/s3/alumnos/sftpuser
      sudo chown root /mnt/s3/alumnos/sftpuser
      sudo chmod g+rx /mnt/s3/alumnos/sftpuser
      mkdir -p /mnt/s3/alumnos/sftpuser/escritura
      mkdir -p /mnt/s3/alumnos/sftpuser/lectura
      chown sftpuser:sftpuser /mnt/s3/alumnos/sftpuser/escritura
      chown ec2-user:sftpuser /mnt/s3/alumnos/sftpuser/lectura
      sudo usermod -a -G sftpuser ec2-user
      ln -s /mnt/s3 /home/ec2-user/s3
      rm -f /mnt/s3/alumnos/sftpuser/.bash_logout /mnt/s3/alumnos/sftpuser/.bash_profile /mnt/s3/alumnos/sftpuser/.bashrc 
      mkdir -p /mnt/s3/profesor
      chown ec2-user:ec2-user /mnt/s3/profesor


  - name: Configuraci贸n del servidor openssh-server
    become: true
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      
      
  - name: Reinicio del servicio SSH
    become: true
    service:
      name: sshd
      state: restarted  
      
  - name: introduccion del script de creacion de usuario
    become: true
    copy:
      src: usuario.sh
      dest: /home/ec2-user/usuario.sh
      mode: 0755